version: '3.9'
services:
 app:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
 mongo:
     image: mongo
     environment:
         - MONGO_INITDB_ROOT_USERNAME=user
         - MONGO_INITDB_ROOT_PASSWORD=password
         - MONGO_INITDB_DATABASE=project
     volumes:
         - mongodb_data:/data/db
 mongo-express:
     image: mongo-express
     environment:
         - ME_CONFIG_MONGODB_SERVER=mongo
         - ME_CONFIG_MONGODB_PORT=27017
         - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
         - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
         - ME_CONFIG_MONGODB_AUTH_USERNAME=user
         - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
         - ME_CONFIG_BASICAUTH_USERNAME=user
         - ME_CONFIG_BASICAUTH_PASSWORD=password
     depends_on:
         - mongo
     ports:
       - "8888:8081"

volumes:
    logs:
        driver: local
    mongodb_data: