port: "8080"

mongo:
  uri: "mongodb://user:password@mongo:27017/"
  db_name: "test"
  workout_collection: "workouts"
  achievement_collection: "achievements"
  goal_collection: "goals"
  user_collection: "users"
  exercise_type: "exercise_type"
auth:
  jwt_key: "salt"